apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/1 * * * *"  # Every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: ubuntu
              command: ["echo", "Hello from CronJob!"]
          restartPolicy: OnFailure