apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: TXJCYW5rZXIK               # base64 encoded value of 'username'
  password: cGFzc3dvcmQ=               # base64 encoded value of 'password'